version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\midstar\proci

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com\mattn\goveralls
 
build_script:
    - go build github.com\midstar\proci
    - go test -v -cover github.com\midstar\proci -coverprofile=coverage.out 
    - goveralls -coverprofile=coverage.out -service=travis-pro -repotoken=%COVERALLS_TOKEN%